### ISSUE TITLE
Getting error after creating an elastic search record

### ISSUE THREAD

**Issue by goluukfgobea** [OCA/search-engine#118]
Hi the company i work for wants to use the module to connect to elastic search on Odoo version 14.0
After adding an elastic search connector backend we get the traceback that follows on additional context.

## Module
[connector_elasticsearch](https://github.com/OCA/search-engine/tree/14.0/connector_elasticsearch)
[connector_search_engine](https://github.com/OCA/search-engine/tree/14.0/connector_search_engine)

## Describe the bug
Error appears when trying to load backends view.

## To Reproduce
**14.0**:
Create a connector for elastic search, then try to enter the root menu for bakcends

1. Go to elastic search
2. Create a connector
3. Save it then click on connectors to return to the tree view on the root action
4. Error raises

**Expected behavior**
We should be able to see the view.

**Additional context**
Python 3.8
Traceback: 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1350, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1369, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 62, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4848, in search_read
    result = records.read(fields)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3022, in read
    return self._read_format(fnames=fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3042, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5675, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4070, in _compute_field_value
    getattr(self, field.compute)()
  File "/mnt/extra-addons/connector_search_engine/models/se_backend.py", line 81, in _compute_specific_backend
    spec_backend._name, spec_backend.id
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1109, in __set__
    self.write(protected_records, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 930, in write
    cache_value = self.convert_to_cache(value, records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2457, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/extra-addons/newrelic/__init__.py", line 57, in _handle_exception
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Wrong value for se.backend.specific_backend: 'se.backend.elasticsearch,3'

**Comment by goluukfgobea** [comment]
Hi, even though this is temp resolvable by changing the view, i wanted to add the bug has to do with the following line:
https://github.com/OCA/search-engine/blob/46996c46eb9a1107b46088ff3339246ad29b8766/connector_search_engine/models/se_backend.py#L80

According to odoo: 
https://www.odoo.com/documentation/14.0/es/developer/reference/addons/orm.html#odoo.fields.Reference
The format of this field should be se.backend.elasticsearch.3 instead of se.backend.elasticsearch,3 (note the difference on the , against the . separator.

Maybe I am wrong and another things has to do with this error.

Thanks and best regards

**Comment by goluukfgobea** [comment]
Another thing I just saw is that even though the reference seems not to work on tree views on form views work perfectly 
It seems it should all work perfectly and it is nust a tree view issue. Maybe killing the field on the tree view is enough 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/100367804/155559106-075b9f58-53f6-40a8-a5f5-ad0b7c3fafe6.png">

**Comment by goluukfgobea** [comment]
Well, do not know what happened, now added the field to the view and is working perfectly, so i am closing the issue 🥺

If you want you can check that but now it works great :(
