### ISSUE TITLE
[16.0] search_engine_image_thumbnail: impossible to create se.image.field.thumbnail.size records

### ISSUE THREAD

**Issue by qgroulard** [OCA/search-engine#183]
## Module
search_engine_image_thumbnail

## Describe the bug
RPC ERROR when trying to create a se.image.field.thumbnail.size from the interface:
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/addons/extendable/models/ir_http.py", line 20, in _dispatch
    return super()._dispatch(endpoint)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/models.py", line 6545, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/models.py", line 6305, in __init__
    self.fetch(name)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/models.py", line 6315, in fetch
    self[name] = record[name]
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/models.py", line 5897, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/fields.py", line 1253, in __get__
    return self.convert_to_record(value, record)
  File "/home/quentin/.virtualenvs/odoo-alphagem/lib/python3.10/site-packages/odoo/addons/base_sparse_field/models/fields.py", line 92, in convert_to_record
    return json.loads(value or "{}")
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://localhost:8069/web/assets/542-a78dbc1/web.assets_backend.min.js:990:274
    makeErrorFromResponse@http://localhost:8069/web/assets/542-a78dbc1/web.assets_backend.min.js:994:163
    jsonrpc/promise</<@http://localhost:8069/web/assets/542-a78dbc1/web.assets_backend.min.js:1002:34
```

## To Reproduce
**Affected versions**: 16.0

1. Go to Search Engine > Thumbnails > Index Thumbnail Sizes 
2. Create a new record

**Additional context**
Same on 16.0 branch and with PR https://github.com/OCA/search-engine/pull/176

**Comment by qgroulard** [comment]
@lmignon I have also tried with the commit used in your project and got the same bug (only it was a step further, when trying to set the `model_id` on the record).
Are you aware of this bug and do you know any workaround ?

**Comment by lmignon** [comment]
@qgroulard Can you try by declaring the  `field_id_domain` as `Binary` in place of `Serialized`? If it doesn't work, the `Serialized` field should work with an additional dependency `base_sparse_field_list_support`

**Comment by lmignon** [comment]
ping @qgroulard
