### ISSUE TITLE
Stack trace in elastic connector

### ISSUE THREAD

**Issue by sbidoul** [OCA/search-engine#22]
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/addons/shopinvader_search_engine/models/shopinvader_backend.py", line 64, in force_resynchronize_index
    self.mapped("se_backend_id.index_ids").resynchronize_all_bindings()
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/addons/connector_search_engine/models/se_index.py", line 171, in resynchronize_all_bindings
    for se_binding in adapter.iter():
  File "/home/odoo-asmartworld-test/instance/venv-3.0.2/lib/python3.5/site-packages/odoo/addons/connector_elasticsearch/components/adapter.py", line 92, in iter
    hits = res["hits"]["hits"]
KeyError: 'hits'
```

**Comment by sbidoul** [comment]
In 12.0

**Comment by sebastienbeau** [comment]
Fix have been merged
